version: '3.8'

services:
  # nats-server:
  #   image: nats:latest
  #   ports:
  #     - '4222:4222'
  #     - '8222:8222'
  #   networks:
  #     - my-network

  # postgres:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: dima
  #     POSTGRES_DB: ai_chatbot_test
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   networks:
  #     - my-network

  redis:
    image: redis:latest
    volumes:
      - redis-data:/data
    networks:
      - my-network
    ports:
      - '6379:6379'
    command: redis-server
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
  # product-crud:
  #   build: ./path/to/product-crud
  #   depends_on:
  #     - postgres
  #     - redis
  #     - nats-server
  #   networks:
  #     - my-network

  # product-api:
  #   build: ./path/to/product-api
  #   depends_on:
  #     - product-crud
  #     - postgres
  #     - redis
  #     - nats-server
  #   networks:
  #     - my-network

  # telegram-bot:
  #   build: ./path/to/telegram-bot
  #   depends_on:
  #     - product-api
  #     - nats-server
  #   networks:
  #     - my-network

networks:
  my-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
